CREATE TABLE store(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(225) NOT NULL,
    address VARCHAR(225) NOT NULL,
    tel VARCHAR(225),
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL
);

